### ISSUE TITLE
map_clean.npy  files does not exist

### ISSUE THREAD

**Issue by alikharrat** [PRBonn/LiDiff#1]
Hello, Hope you are doing well.

Trying to run some experiments after making a container work and the environments is work. i got this error:

FileNotFoundError: [Errno 2] No such file or directory: '/workspace/dataset/sequences/00/map_clean.npy'

How can i generate this file? (what preprocess should be done, to get that file)

thank you

**Comment by nuneslu** [comment]
Thanks for the interest in our work! To generate the map you should run the map_from_scans.py script. I will soon update the README.md to add also those details. :)

**Comment by alikharrat** [comment]
thank you, for the answer, great work by the way !!

**Comment by nuneslu** [comment]
I have just updated the `README.md` with more information now. I will close this issue for now but fell free to reopen it if needed. :)
