### ISSUE TITLE
provide test code?

### ISSUE THREAD

**Issue by GG-Bonds** [PRBonn/LiDiff#17]
Although I found the eval_path.py code, it does not allow one-click permission. I don’t know if it is your correct test code.

**Comment by GG-Bonds** [comment]
> Sorry, could you clarify what do you mean by "one-click permission"? Does it throw any error?

An error will be reported when running. Need the code in eval_path.py to work properly.

**Comment by nuneslu** [comment]
Hi, I have checked the code for evaluation now and you are right, some minors were needed to make it run. You can pull the repo now and the code should run normally as `python3 utils/eval_path.py --path PATH`
