### ISSUE TITLE
Compute Requirements

### ISSUE THREAD

**Issue by va1bhavagrawal** [PRBonn/LiDiff#19]
Hey! Thanks for the great work!

Could you please elaborate on the compute requirements, both for training and inference. Specifically, please elaborate on the following:
- the name of the GPU used.
- the number of GPUs used for training.
- the time to train on a specific dataset (say, SemanticKITTI).

Thanks!

**Comment by nuneslu** [comment]
Hi! Thanks for the interest in our paper. These are the compute [specifications](https://github.com/PRBonn/LiDiff/issues/7#issuecomment-2049093845).
