### ISSUE TITLE
Ground Truth Geneartion process taking too long

### ISSUE THREAD

**Issue by Yacovitch** [PRBonn/LiDiff#2]
Hi,

First of all, thank you for your work! It is very inspiring.

I am in the process of ground truth generation, but completing each sequence takes 2~6 hours. Is it normal?

**Comment by EllingtonKirby** [comment]
I was able to speed up the `map_from_scans.py` script significantly by moving some operations to the GPU. Would you be interested in a PR for this?

**Comment by nuneslu** [comment]
@EllingtonKirby sure! Would be really nice, you can create the PR and I will check it. Thanks!
