### ISSUE TITLE
Python version

### ISSUE THREAD

**Issue by va1bhavagrawal** [PRBonn/LiDiff#20]
Hi!

It seems that the packages listed in requirements.txt are very outdated, and are not available on all the python versions when installing with miniconda and pip. Could you please tell the python version which you had used?

If possible, also outline the environment setup procedure that you had followed. 

Thanks!

**Comment by va1bhavagrawal** [comment]
particularly, this is the error i am facing:

![image](https://github.com/PRBonn/LiDiff/assets/102590952/b506c1e1-f8bf-44ac-9910-e023f74a61d3)

**Comment by nuneslu** [comment]
Hi, we have used python 3.8.18

In this [issue](https://github.com/PRBonn/LiDiff/issues/6#issuecomment-2042724797) people have faced similar error and managed to solve.
