### ISSUE TITLE
max_range in the training script

### ISSUE THREAD

**Issue by t-martyniuk** [PRBonn/LiDiff#23]
Hello! 
Could you please tell me why in this line of the training script - https://github.com/PRBonn/LiDiff/blob/baab39d27583dcc6e2745cacde98504b2ace7990/lidiff/train.py#L68
you are using the value 10., if throughout the whole paper / codebase it was always radius = 50.?
is it just a legacy line from one of the previous setups? or is it actually meant to be invoked at any point over the default 50.?

**Comment by nuneslu** [comment]
Hi, this if statement only sets the range to 10m if the max_range is not define in the config file. Since this is defined as 50m in the config.yaml this line will be ignored.

**Comment by t-martyniuk** [comment]
ok, thank you!
