### ISSUE TITLE
终端运行时报错

### ISSUE THREAD

**Issue by liudun226296** [PRBonn/LiDiff#25]
(base) root@autodl-container-433f409b5c-cc8408c2:~/autodl-tmp/LiDiff/lidiff# python3 tools/diff_completion_pipeline.py --diff DIFF_CKPT --refine REFINE_CKPT -T DENOISING_STEPS -s CONDITIONING_WEIGHT
Traceback (most recent call last):
  File "tools/diff_completion_pipeline.py", line 4, in <module>
    import lidiff.models.minkunet as minknet
ModuleNotFoundError: No module named 'lidiff'

**Comment by nuneslu** [comment]
Hi, did you follow  the instructions (here)[https://github.com/PRBonn/LiDiff?tab=readme-ov-file#dependencies]. It seems that you haven't installed the repo properly.
