### ISSUE TITLE
Why the loss stuck at around 0.9 ?

### ISSUE THREAD

**Issue by Brosy-qj** [PRBonn/LiDiff#27]
Hi,
I found that the loss stuck at around 0.9, but the results kept improving. Does this mean that every step will result in an error of 0.9?However, in reality, the generated point cloud has only a small error. How should I understand this phenomenon?

**Comment by RoboticsZhang** [comment]
The same in my attempt either. Wondering why - . -

**Comment by nuneslu** [comment]
Hi! This is the normal behavior for the diffusion loss during training. You can check [this](https://github.com/PRBonn/LiDiff/issues/21#issuecomment-2179784813) previous issue for further comments on it and [this](https://github.com/huggingface/diffusers/issues/3604)related issue on another repo.
