### ISSUE TITLE
ModuleNotFoundError: No module named 'pcdiff'

### ISSUE THREAD

**Issue by Yacovitch** [PRBonn/LiDiff#3]
Hi, I am trying to train your model with KITTI-Semantic, but it cannot find module 'pcdiff'. Am I missing something?

**Comment by nuneslu** [comment]
Hi, sorry for this error. Actually I have renamed the repo from "pcdiff" to "lidiff" before releasing the code and I forgot to change some imports. I just fixed it so you can pull and it should be working now.

**Comment by Yacovitch** [comment]
Code is working after replacing pcdiff into lidiff. Thank you
