### ISSUE TITLE
"decay" in configuring the optimizer

### ISSUE THREAD

**Issue by t-martyniuk** [PRBonn/LiDiff#31]
Hello!
I have a question about the optimizer used.

In the paper it says
> As optimizer, we used Adam [13] with a learning rate of 10−4 decreased by half every 5 epochs, and decay of 10−4, with batch size equal to 2.

although in the code you don't set the weight_decay.

Which one is to be regarded as the ultimate source of truth?

Thank you.

**Comment by nuneslu** [comment]
Hi, we in fact used decay of 10-4 for the paper experiments, however later we noticed that with or without decay the results were the same.
