### ISSUE TITLE
Unable to reproduce the article's results or metrics

### ISSUE THREAD

**Issue by Lihua101** [PRBonn/LiDiff#36]
First of all, I would like to express my sincere gratitude for your valuable work, which has provided me with new research insights. However, I encountered some difficulties when evaluating the model using the provided weights. Specifically, when I used the refinement weights to replicate the results, I obtained IOU values of 16%, 11%, and 6% at Voxel sizes of 0.5m, 0.2m, and 0.1m, respectively, rather than the reported values of 40.71%, 38.92%, and 24.75% in your paper.

Could you kindly provide the original weight file used in your paper for the metrics mentioned? I would greatly appreciate your assistance.

Thank you again for your work and your time.
![屏幕截图 2024-12-18 211319](https://github.com/user-attachments/assets/f26805ec-08b8-4379-9210-2c070be6c4d2)
<img width="947" alt="微信图片_20241218211336" src="https://github.com/user-attachments/assets/0244b730-12d1-404d-bd24-315061ee10d9" />

**Comment by nuneslu** [comment]
I would suggest reverting any changes you did in the code and also git pulling the latest version of the code. This error is strange to me since I cannot reproduce it and also other people could already reproduce the results we reported in the paper.
