### ISSUE TITLE
data: num_points

### ISSUE THREAD

**Issue by Yacovitch** [PRBonn/LiDiff#8]
Dear Author,

data: num_points in config.yaml means the maximum number that the network can take as input? or gt?

**Comment by nuneslu** [comment]
Hi! During training `num_points` refers to both the input and the ground truth. We random sample `num_points` from the ground truth map and add noise to it for the network to learn to denoise it.

**Comment by Yacovitch** [comment]
Hi, Thank you for the reply. How do you match the input scan (P in the supplementary material Figure 1) and ground truth (gt in Figure 1) if num_points are randomly sampled?

**Comment by nuneslu** [comment]
We condition the noise prediction of each noisy point from the ground truth to the closest point in the conditioning point cloud. The match is done by the distance, and we just consider the closest one for the conditioning.

**Comment by Yacovitch** [comment]
So does that mean, in the training phase, scans from Kitti-semantic are not used, but inputs and their gts are sampled from clean_map.npy generated from map_from_scan.py?

**Comment by nuneslu** [comment]
Hi! The kitti scans are used as the conditioning P (in Figure 1 from the supplement) and Gt is the ground truth from `map_from_scan.py` with added noise.
